### ISSUE TITLE
Dateiname zu lang

### ISSUE THREAD

**Issue by steprobst** [ffharz/Dokumente#1]
@Yoneo der Dateiname https://github.com/ffharz/Dokumente/blob/master/Presse/NDR/20160603_Harzer_Freifunk_Zwischen_Gipfeln_ins_Netz_NDR.de_-_Nachrichten_-_Niedersachsen_-_Braunschweig_Harz_G%C3%B6ttingen_-_2016-06-04_10.42.38.png ist zu lang. Kannst du den bitte ein deinem Repo einkürzen und erneut pushen?

Mfg
Steffen

**Comment by Yoneo** [comment]
jo, wurde erledigt.
